# Generated by Django 4.1 on 2022-09-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='header_image',
        ),
    ]
